### ISSUE TITLE
Issue checking by absolute file path

### ISSUE THREAD

**Issue by Bangertm** [Mermade/check_api#1]
I'm having an issue attempting to check a local file referenced by an absolute file path.  Relative file paths seem to work fine.  

For example:: `check_api C:\Users\ban59317\AppData\Local\Temp\tmpvhpaqb.json`

I think the issue has to do with [this check](https://github.com/Mermade/check_api/blob/master/check_api.js#L56).  `u.protocol` seems to be picking up `c:` in this case and then the subsequent `fetch` is throwing an error.  

Changing the line to `if (u.protocol && u.protocol.startsWith('http')) {` works for me, but I may be missing something or maybe there is a better way to handle this.

**Comment by MikeRalphson** [comment]
Thanks for reporting. I think your proposed fix is the way to go.
